// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DewiAPI.Models;

public partial class Contact
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string EmailId { get; set; }

    public string Subject { get; set; }

    public string Message { get; set; }
    public string PhoneNumber { get; set; }
}